openapi: 3.0.3
info:
  title: ProceduraAI API
  description: API for Screen Recording & SOP Generation
  version: 1.0.0

servers:
  - url: https://{project}.supabase.co
    description: Supabase API
    variables:
      project:
        default: your-project-ref

paths:
  # ============================================
  # PROCEDURES
  # ============================================
  /rest/v1/procedures:
    get:
      summary: List user's procedures
      tags: [Procedures]
      security:
        - bearerAuth: []
      parameters:
        - name: select
          in: query
          schema:
            type: string
            default: id,title,status,step_count,thumbnail_url,created_at,views_count,is_public
        - name: order
          in: query
          schema:
            type: string
            default: created_at.desc
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of procedures
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProcedureListItem'

    post:
      summary: Create new procedure (start recording)
      tags: [Procedures]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title]
              properties:
                title:
                  type: string
                  maxLength: 200
                  example: "Como cadastrar cliente"
                description:
                  type: string
                  example: "Processo de cadastro no CRM"
      responses:
        '201':
          description: Procedure created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Procedure'

  /rest/v1/procedures?id=eq.{id}:
    get:
      summary: Get procedure by ID
      tags: [Procedures]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: select
          in: query
          schema:
            type: string
            default: "*,steps(*)"
      responses:
        '200':
          description: Procedure with steps
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcedureWithSteps'

    patch:
      summary: Update procedure
      tags: [Procedures]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                is_public:
                  type: boolean
                status:
                  $ref: '#/components/schemas/ProcedureStatus'
      responses:
        '200':
          description: Procedure updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Procedure'

    delete:
      summary: Delete procedure
      tags: [Procedures]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Procedure deleted

  /rest/v1/procedures?public_slug=eq.{slug}:
    get:
      summary: Get public procedure by slug
      tags: [Procedures]
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
        - name: select
          in: query
          schema:
            type: string
            default: "id,title,description,step_count,created_at,steps(order_index,annotated_screenshot_url,generated_text,manual_text)"
      responses:
        '200':
          description: Public procedure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicProcedure'

  # ============================================
  # STEPS
  # ============================================
  /rest/v1/steps:
    post:
      summary: Add step to procedure
      tags: [Steps]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StepCreate'
      responses:
        '201':
          description: Step created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Step'

  /rest/v1/steps?id=eq.{id}:
    patch:
      summary: Update step (edit text)
      tags: [Steps]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                manual_text:
                  type: string
                  maxLength: 2000
                order_index:
                  type: integer
                  minimum: 1
      responses:
        '200':
          description: Step updated

    delete:
      summary: Delete step
      tags: [Steps]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Step deleted

  # ============================================
  # EDGE FUNCTIONS
  # ============================================
  /functions/v1/process-procedure:
    post:
      summary: Process procedure with AI
      description: Generates AI descriptions and annotations for all steps
      tags: [Processing]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [procedure_id]
              properties:
                procedure_id:
                  type: string
                  format: uuid
      responses:
        '200':
          description: Processing started
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '402':
          description: Insufficient credits
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /functions/v1/generate-pdf:
    post:
      summary: Generate PDF export
      tags: [Export]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [procedure_id]
              properties:
                procedure_id:
                  type: string
                  format: uuid
      responses:
        '200':
          description: PDF generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  download_url:
                    type: string
                    format: uri
                  expires_at:
                    type: string
                    format: date-time

  /functions/v1/share-procedure:
    post:
      summary: Generate or get public share link
      tags: [Sharing]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [procedure_id]
              properties:
                procedure_id:
                  type: string
                  format: uuid
      responses:
        '200':
          description: Share link generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  public_url:
                    type: string
                    format: uri
                    example: "https://procedura.ai/p/abc123xyz"
                  slug:
                    type: string
                    example: "abc123xyz"

  /functions/v1/increment-views:
    post:
      summary: Increment view count for public procedure
      tags: [Analytics]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [slug]
              properties:
                slug:
                  type: string
      responses:
        '200':
          description: View counted

  # ============================================
  # USER
  # ============================================
  /rest/v1/users?id=eq.{id}:
    get:
      summary: Get user profile
      tags: [User]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    patch:
      summary: Update user profile
      tags: [User]
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                avatar_url:
                  type: string
                  format: uri
      responses:
        '200':
          description: Profile updated

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ProcedureStatus:
      type: string
      enum: [draft, recording, processing, ready, error]

    ActionType:
      type: string
      enum: [click, input, navigate, scroll, select]

    Plan:
      type: string
      enum: [free, starter, pro, business]

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string
        avatar_url:
          type: string
          format: uri
        plan:
          $ref: '#/components/schemas/Plan'
        credits_remaining:
          type: integer
        credits_reset_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time

    Procedure:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        status:
          $ref: '#/components/schemas/ProcedureStatus'
        processing_progress:
          type: integer
          minimum: 0
          maximum: 100
        is_public:
          type: boolean
        public_slug:
          type: string
        views_count:
          type: integer
        step_count:
          type: integer
        thumbnail_url:
          type: string
          format: uri
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ProcedureListItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        status:
          $ref: '#/components/schemas/ProcedureStatus'
        step_count:
          type: integer
        thumbnail_url:
          type: string
        created_at:
          type: string
          format: date-time
        views_count:
          type: integer
        is_public:
          type: boolean

    ProcedureWithSteps:
      allOf:
        - $ref: '#/components/schemas/Procedure'
        - type: object
          properties:
            steps:
              type: array
              items:
                $ref: '#/components/schemas/Step'

    PublicProcedure:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        step_count:
          type: integer
        created_at:
          type: string
          format: date-time
        steps:
          type: array
          items:
            $ref: '#/components/schemas/PublicStep'

    Step:
      type: object
      properties:
        id:
          type: string
          format: uuid
        procedure_id:
          type: string
          format: uuid
        order_index:
          type: integer
        screenshot_url:
          type: string
        annotated_screenshot_url:
          type: string
        action_type:
          $ref: '#/components/schemas/ActionType'
        element_selector:
          type: string
        element_text:
          type: string
        element_tag:
          type: string
        click_x:
          type: integer
        click_y:
          type: integer
        page_url:
          type: string
          format: uri
        page_title:
          type: string
        generated_text:
          type: string
        manual_text:
          type: string
        captured_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time

    StepCreate:
      type: object
      required: [procedure_id, order_index, action_type, page_url, captured_at]
      properties:
        procedure_id:
          type: string
          format: uuid
        order_index:
          type: integer
          minimum: 1
        screenshot_url:
          type: string
        action_type:
          $ref: '#/components/schemas/ActionType'
        element_selector:
          type: string
        element_text:
          type: string
          maxLength: 500
        element_tag:
          type: string
        click_x:
          type: integer
        click_y:
          type: integer
        page_url:
          type: string
          format: uri
        page_title:
          type: string
        captured_at:
          type: string
          format: date-time

    PublicStep:
      type: object
      properties:
        order_index:
          type: integer
        annotated_screenshot_url:
          type: string
        generated_text:
          type: string
        manual_text:
          type: string

    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        code:
          type: string
